Repository Khushi-Nigam/jobportal, pull requests merged in 2025-08, with the labels that each got.

#92 BUG FIX - Make Login Button Functional #76
  employer/models.py
  employer/static/default-avatar.png
  employer/templates/employerparent.html
  employer/views.py
  jobapp/templates/employer.html
  jobapp/views.py
  jsapp/jsappurls.py
  jsapp/views.py
Labels: gssoc'25, level 2

#98 fixed the latest job section and header section
  jobapp/templates/index.html
  jobapp/templates/parent.html
Labels: gssoc'25, level 2

#95 Rearranged YouTube Videos Using Grid Layout
  jobapp/templates/services.html
Labels: gssoc'25, level 2

#105 updated index page css with animations
  jobapp/templates/index.html
  myenv/bin/Activate.ps1
  myenv/bin/activate
  myenv/bin/activate.csh
  myenv/bin/activate.fish
  myenv/bin/django-admin
  myenv/bin/gunicorn
  myenv/bin/pip
  myenv/bin/pip3
  myenv/bin/pip3.12
  myenv/bin/python
  myenv/bin/python3
  myenv/bin/python3.12
  myenv/bin/sqlformat
  myenv/pyvenv.cfg
Labels: gssoc'25, level 3

#116 Fixed View Profile bug and added save button
  employer/migrations/0003_employer.py
  jsapp/templates/jshome.html
  jsapp/templates/viewprofile.html
  jsapp/views.py
Labels: good first issue, gssoc'25, level 2

#109 Fix AJAX search and enhance job search experience
  jobapp/jobappurls.py
  jobapp/templates/index.html
  jobapp/views.py
  jobportal/settings.py
Labels: gssoc'25, level 2

#114 Issue #5 resolved
  jobapp/templates/aboutus.html
  jobapp/templates/apply.html
  jobapp/templates/blog.html
  jobapp/templates/contactus.html
  jobapp/templates/index.html
  jobapp/templates/parent.html
  jobapp/templates/services.html
Labels: gssoc'25, level 2

#125 Update index.html #123
  jobapp/templates/index.html
Labels: gssoc'25, level 2

#124 Update blog.html #123
  jobapp/templates/blog.html
Labels: gssoc'25, level 2

#126 Made improvements and solved bugs of issue #99
  jsapp/templates/jsparent.html
Labels: gssoc'25, level 2

#135 Removed the ui-fixes in the home page
  jobapp/templates/index.html
Labels: gssoc'25, level 1

#136 Enhanced the footer section
  jobapp/templates/parent.html
Labels: gssoc'25, level 1

#145 Improve Registration Validation and Restrict Resume Uploads
  jobapp/templates/jobseeker.html
Labels: gssoc'25, level 2

#156 Update jobseeker.html #102
  jobapp/templates/jobseeker.html
Labels: gssoc'25, level 1

#157 Added navbar styling as inline styling and also commented overflow-x in container in aboutus.
  jobapp/templates/aboutus.html
  jobapp/templates/parent.html
Labels: gssoc'25, level 1

#161 Fix: Profile Management Button for Employer & Jobseeker
  employer/templates/employerparent.html
  jsapp/templates/jsparent.html
Labels: gssoc'25, level 2

#169 making text clear on about-us page in the footer
  jobapp/templates/aboutus.html
  jobapp/templates/parent.html
  jobapp/templates/services.html
Labels: gssoc'25, level 1

#172 Fix: Upload Resume button now shows popup and redirects to login if not authenticated
  jobapp/templates/index.html
Labels: gssoc'25, level 1

#189 Update changepassword.html #179
  jsapp/templates/changepassword.html
Labels: gssoc'25, level 1

#191 fix: register btn working on all pages
  jobapp/templates/aboutus.html
  jobapp/templates/blog.html
  jobapp/templates/contactus.html
  jobapp/templates/index.html
  jobapp/templates/services.html
Labels: gssoc'25, level 1

#192 fix: improve layout of checkbox and submit button of employeer.
  jobapp/templates/employer.html
Labels: gssoc'25, level 2

#198 login toggle button to see password solved
  jobapp/templates/login.html
  myenv/pyvenv.cfg
Labels: gssoc'25, level 1

#199 Fix: Password visibility toggle functionality on login page
  jobapp/templates/login.html
Labels: gssoc'25, level 1
