Repository Khushi-Nigam/jobportal, pull requests merged in 2025-07, with the labels that each got.

#23 Login UI redesign with cleanup (#8)
  jobapp/templates/login.html
  jobapp/templates/parent.html
Labels: enhancement, gssoc'25, level 1

#29 Add License and Update README
  LICENSE
  README.md
Labels: good first issue, gssoc'25, level 3

#28 Updated header and footer and added hover effects to service cards
  jobapp/templates/index.html
  jobapp/templates/parent.html
  jobapp/templates/services.html
Labels: gssoc'25, level 2

#59 fix/.gitignore #58
  .gitignore
Labels: gssoc'25, level 2

#65 #issue 26 / 39 Redesign employer registration form UI to match jobseeker
  jobapp/templates/employer.html
Labels: gssoc'25, level 2

#64 Feature/navbar hover effect
  adminapp/__pycache__/__init__.cpython-312.pyc
  adminapp/__pycache__/admin.cpython-312.pyc
  adminapp/__pycache__/adminappurls.cpython-312.pyc
  adminapp/__pycache__/apps.cpython-312.pyc
  adminapp/__pycache__/models.cpython-312.pyc
  adminapp/__pycache__/views.cpython-312.pyc
  adminapp/migrations/__pycache__/0001_initial.cpython-312.pyc
  adminapp/migrations/__pycache__/__init__.cpython-312.pyc
  employer/__pycache__/__init__.cpython-312.pyc
  employer/__pycache__/admin.cpython-312.pyc
  employer/__pycache__/apps.cpython-312.pyc
  employer/__pycache__/employerurls.cpython-312.pyc
  employer/__pycache__/models.cpython-312.pyc
  employer/__pycache__/views.cpython-312.pyc
  employer/migrations/__pycache__/0001_initial.cpython-312.pyc
  employer/migrations/__pycache__/0002_jobs_postedby.cpython-312.pyc
  employer/migrations/__pycache__/0003_remove_jobs_postedby.cpython-312.pyc
  employer/migrations/__pycache__/0004_post.cpython-312.pyc
  employer/migrations/__pycache__/0005_remove_post_profilepic_post_posteddate.cpython-312.pyc
  employer/migrations/__pycache__/0006_alter_post_caption.cpython-312.pyc
  employer/migrations/__pycache__/0007_post_cpemailaddress_post_cpname.cpython-312.pyc
  employer/migrations/__pycache__/0008_remove_post_cpemailaddress.cpython-312.pyc
  employer/migrations/__pycache__/0009_alter_jobs_location_alter_jobs_qualification.cpython-312.pyc
  employer/migrations/__pycache__/0010_jobs_job_tags.cpython-312.pyc
  employer/migrations/__pycache__/__init__.cpython-312.pyc
  jobapp/__pycache__/__init__.cpython-312.pyc
  jobapp/__pycache__/admin.cpython-312.pyc
  jobapp/__pycache__/apps.cpython-312.pyc
  jobapp/__pycache__/jobappurls.cpython-312.pyc
  jobapp/__pycache__/models.cpython-312.pyc
  jobapp/__pycache__/views.cpython-312.pyc
  jobapp/migrations/__pycache__/0001_initial.cpython-312.pyc
  jobapp/migrations/__pycache__/0002_jobseeker_profilepic.cpython-312.pyc
  jobapp/migrations/__pycache__/0003_alter_jobseeker_regdate.cpython-312.pyc
  jobapp/migrations/__pycache__/0004_employer_empprofilepic.cpython-312.pyc
  jobapp/migrations/__pycache__/0005_alter_employer_regdate.cpython-312.pyc
  jobapp/migrations/__pycache__/0006_tags_jobseeker_seeker_tags.cpython-312.pyc
  jobapp/migrations/__pycache__/__init__.cpython-312.pyc
  jobapp/templates/parent.html
  jobportal/__pycache__/__init__.cpython-312.pyc
  jobportal/__pycache__/settings.cpython-312.pyc
  jobportal/__pycache__/urls.cpython-312.pyc
  jobportal/__pycache__/wsgi.cpython-312.pyc
  jsapp/__pycache__/__init__.cpython-312.pyc
  jsapp/__pycache__/admin.cpython-312.pyc
  jsapp/__pycache__/apps.cpython-312.pyc
  jsapp/__pycache__/jsappurls.cpython-312.pyc
  jsapp/__pycache__/models.cpython-312.pyc
  jsapp/__pycache__/views.cpython-312.pyc
  jsapp/migrations/__pycache__/0001_initial.cpython-312.pyc
  jsapp/migrations/__pycache__/0002_response.cpython-312.pyc
  jsapp/migrations/__pycache__/0003_remove_appliedjobs_id_alter_appliedjobs_jobtitle.cpython-312.pyc
  jsapp/migrations/__pycache__/0004_appliedjobs_id_alter_appliedjobs_jobtitle.cpython-312.pyc
  jsapp/migrations/__pycache__/0005_alter_appliedjobs_id.cpython-312.pyc
  jsapp/migrations/__pycache__/0006_alter_response_emailaddress_savedjob.cpython-312.pyc
  jsapp/migrations/__pycache__/__init__.cpython-312.pyc
  venv/pyvenv.cfg
Labels: gssoc'25, level 1, easy

#63 Job card layout & hover effect
  jobapp/templates/index.html
Labels: gssoc'25, level 2, medium

#73 Added job filter feature with location, experience, and job type filters
  adminapp/templates/viewjobs.html
Labels: good first issue, gssoc'25, level 2

#77 Add "Back to Top" Links in README for Better Navigation
  README.md
Labels: gssoc'25, level 1

#72 added linkedin button as new login feature
  jobapp/templates/login.html
Labels: gssoc'25, level 1
